parameters:

services:
    phone_book_api.controller.city:
        class: Monastyryov\PhoneBookApiBundle\Controller\CityController
        arguments:
            - "@phone_book.service.city"
        calls:
            - [ "setContainer", [ "@service_container" ]]

    phone_book_api.controller.record:
        class: Monastyryov\PhoneBookApiBundle\Controller\RecordController
        arguments:
            - "@phone_book.service.record"
        calls:
            - [ "setContainer", [ "@service_container" ]]