imports:
    - { resource: factories.yml }
    - { resource: repositories.yml }

parameters:

services:
    phone_book.service.record:
        class: Monastyryov\PhoneBookBundle\Service\RecordService
        arguments:
            - "@phone_book.repository.record"
            - "@phone_book.service.street"
            - "@phone_book.factory.record"
            - "@logger"

    phone_book.service.street:
        class: Monastyryov\PhoneBookBundle\Service\StreetService
        arguments:
            - "@phone_book.repository.street"
            - "@logger"

    phone_book.service.city:
        class: Monastyryov\PhoneBookBundle\Service\CityService
        arguments:
            - "@phone_book.repository.city"