imports:
    - { resource: factories.yml }
    - { resource: repositories.yml }

parameters:

services:
    phone_book.service.record:
      class: Monastyryov\PhoneBookBundle\Service\RecordService
      arguments:
          - "@phone_book.repository.record"